package com.kotak.inventoryservice.Dao;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import lombok.Data;
import software.amazon.awssdk.enhanced.dynamodb.mapper.annotations.DynamoDbBean;
import software.amazon.awssdk.enhanced.dynamodb.mapper.annotations.DynamoDbPartitionKey;
import java.math.BigDecimal;
import java.time.Instant;
import java.time.LocalTime;
import java.util.List;

@DynamoDbBean
@Data
public class Order {
    public static final String TABLE_NAME = "order";

    private String id;
    private BigDecimal price;
    private BigDecimal quantity;
    private String status;
    private Instant createdAt;
    private Instant updatedAt;
    private List<ProductDetails> products;


    @DynamoDbPartitionKey
    @DynamoDBAutoGeneratedKey
    public String getId() {
        return id;
    }

    @DynamoDBAttribute(attributeName = "price")
    public BigDecimal getPrice() {
        return price;
    }

    @DynamoDBAttribute(attributeName = "status")
    public String getStatus() {
        return status;
    }

    @DynamoDBAutoGeneratedTimestamp(strategy= DynamoDBAutoGenerateStrategy.ALWAYS)
    public LocalTime getUpdatedAt()
    {
        return LocalTime.now();
    }

    @DynamoDBAutoGeneratedTimestamp(strategy=DynamoDBAutoGenerateStrategy.CREATE)
    public LocalTime getCreatedAt() {return LocalTime.now();}

    @DynamoDBDocument
    public class ProductDetails
    {
        @DynamoDBAttribute(attributeName = "id")
        private String id;
        @DynamoDBAttribute(attributeName = "quantity")
        private int quantity;
    }

}

